# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
    format_listener:
        rules:
            - { path: ^/api/, priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', '*/*' ], fallback_format: html, prefer_extension: true }
